---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-test
resources:
  - ns.yaml
  - my-test-quota.yaml
  - my-test-deploy.yaml
  - my-test-svc.yaml
  - my-test-vs.yaml
  - my-test-hpa.yaml
