---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: my-test-quota
  namespace: my-test
  labels:
    kubernetes.io/metadata.name: my-test
    backstage.io/kubernetes-id: my-test
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
