---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: aaaaaaa-quota
  namespace: aaaaaaa
  labels:
    kubernetes.io/metadata.name: aaaaaaa
    backstage.io/kubernetes-id: aaaaaaa
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
