---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: golang-test-app-2-quota
  namespace: golang-test-app-2
  labels:
    kubernetes.io/metadata.name: golang-test-app-2
    backstage.io/kubernetes-id: golang-test-app-2
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
